"""Append masking + t-SNE cells to the paper notebook."""
import json, pathlib

nb_path = pathlib.Path("notebooks/09_paper_visualizations.ipynb")
with open(nb_path, encoding="utf-8") as f:
    nb = json.load(f)

# ── markdown: masking ──────────────────────────────────────────────────
md_masking = {
    "cell_type": "markdown",
    "metadata": {},
    "source": (
        "## 14. U-Net Segmentation — Egg Region Masking\n\n"
        "Visualisasi hasil segmentasi U-Net pada gambar candling:\n"
        "- **Kolom 1**: Gambar raw asli\n"
        "- **Kolom 2**: Binary mask output U-Net\n"
        "- **Kolom 3**: Overlay berwarna (Biru=Class1, Merah=Class2 embryo/vaskular)\n"
        "- **Kolom 4**: Hasil masking\n\n"
        "> Telur **subur** menunjukkan struktur vaskular (merah), "
        "telur **tidak subur** menghasilkan mask kosong."
    ),
}

# ── code: masking ──────────────────────────────────────────────────────
masking_code = (
    "import cv2, pathlib, numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "from matplotlib.patches import Patch\n"
    "\n"
    "BG = '#FAFAFA'\n"
    "RAW = pathlib.Path('../data/raw/Dataset1_JPG-20260128T021855Z-3-001/Dataset1_JPG')\n"
    "\n"
    "def crop_to_egg(img, margin=80):\n"
    "    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) if img.ndim == 3 else img\n"
    "    _, th = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)\n"
    "    coords = cv2.findNonZero(th)\n"
    "    if coords is None:\n"
    "        return img, (0, 0, img.shape[1], img.shape[0])\n"
    "    x, y, w, h = cv2.boundingRect(coords)\n"
    "    x1, y1 = max(0, x-margin), max(0, y-margin)\n"
    "    x2, y2 = min(img.shape[1], x+w+margin), min(img.shape[0], y+h+margin)\n"
    "    return img[y1:y2, x1:x2], (x1, y1, x2, y2)\n"
    "\n"
    "def make_overlay(raw_bgr, mask, size=360):\n"
    "    img_rgb = cv2.cvtColor(raw_bgr, cv2.COLOR_BGR2RGB)\n"
    "    crop_raw, (x1,y1,x2,y2) = crop_to_egg(raw_bgr, 80)\n"
    "    crop_mask = mask[y1:y2, x1:x2]\n"
    "    crop_rgb  = img_rgb[y1:y2, x1:x2]\n"
    "    h, w = crop_rgb.shape[:2]\n"
    "    scale = size / max(h, w)\n"
    "    nh, nw = int(h*scale), int(w*scale)\n"
    "    disp_img  = cv2.resize(crop_rgb,  (nw, nh))\n"
    "    disp_mask = cv2.resize(crop_mask, (nw, nh), interpolation=cv2.INTER_NEAREST)\n"
    "    binary    = (disp_mask > 0).astype(np.uint8) * 255\n"
    "    overlay   = disp_img.astype(float) / 255.0\n"
    "    alpha = 0.45\n"
    "    for cls, col in [(1,(0.2,0.6,1.0)), (2,(1.0,0.3,0.2))]:\n"
    "        where = disp_mask == cls\n"
    "        if where.any():\n"
    "            for c, v in enumerate(col):\n"
    "                overlay[:,:,c][where] = (1-alpha)*overlay[:,:,c][where] + alpha*v\n"
    "    masked_out = disp_img.copy()\n"
    "    masked_out[binary == 0] = 0\n"
    "    return disp_img, binary, (overlay*255).astype(np.uint8), masked_out\n"
    "\n"
    "fertile_samples, infertile_samples = [], []\n"
    "for sp in ['train','val','test']:\n"
    "    mask_dir = pathlib.Path(f'../data/segmentation/{sp}/masks')\n"
    "    if not mask_dir.exists(): continue\n"
    "    for mp in sorted(mask_dir.glob('*.png')):\n"
    "        rp = RAW / mp.name.replace('.png','.jpg')\n"
    "        if not rp.exists(): continue\n"
    "        m = cv2.imread(str(mp), cv2.IMREAD_GRAYSCALE)\n"
    "        if m is not None and m.max() > 0:\n"
    "            fertile_samples.append((rp, mp, sp, 'Fertile'))\n"
    "    if len(fertile_samples) >= 3: break\n"
    "for sp in ['train','val','test']:\n"
    "    img_dir  = pathlib.Path(f'../data/preprocessed/{sp}/infertile')\n"
    "    mask_dir = pathlib.Path(f'../data/segmentation/{sp}/masks')\n"
    "    if not img_dir.exists(): continue\n"
    "    for ip in sorted(img_dir.glob('*.jpg'))[:5]:\n"
    "        rp = RAW / ip.name\n"
    "        mp = mask_dir / (ip.stem+'.png')\n"
    "        if rp.exists():\n"
    "            infertile_samples.append((rp, mp if mp.exists() else None, sp, 'Infertile'))\n"
    "    if len(infertile_samples) >= 3: break\n"
    "\n"
    "all_samples = fertile_samples[:3] + infertile_samples[:3]\n"
    "colors      = ['#2196F3']*3 + ['#F44336']*3\n"
    "n = len(all_samples)\n"
    "col_labels  = ['Original (Raw)', 'Binary Mask (U-Net)',\n"
    "               'Overlay (Blue=Boundary, Red=Embryo)', 'Masked Egg Region']\n"
    "\n"
    "fig, axes = plt.subplots(n, 4, figsize=(13, 3.4*n+1), facecolor=BG)\n"
    "fig.suptitle('U-Net Segmentation Results - Egg Region Masking\\n'\n"
    "             'Fertile (rows 1-3) vs Infertile (rows 4-6)',\n"
    "             fontsize=13, fontweight='bold')\n"
    "for col, lbl in enumerate(col_labels):\n"
    "    axes[0,col].set_title(lbl, fontsize=10, fontweight='bold', pad=6)\n"
    "for row,(rp,mp,sp,cls) in enumerate(all_samples):\n"
    "    c = colors[row]\n"
    "    raw_bgr = cv2.imread(str(rp))\n"
    "    mask = (cv2.imread(str(mp), cv2.IMREAD_GRAYSCALE)\n"
    "            if mp and pathlib.Path(str(mp)).exists()\n"
    "            else np.zeros(raw_bgr.shape[:2], np.uint8))\n"
    "    orig, binary, overlay, masked = make_overlay(raw_bgr, mask, 360)\n"
    "    cov = (mask>0).sum()/mask.size*100\n"
    "    for col,(ax,im,cm) in enumerate(zip(axes[row],\n"
    "            [orig,binary,overlay,masked],[None,'gray',None,None])):\n"
    "        ax.set_facecolor('#111')\n"
    "        ax.imshow(im, cmap=cm,\n"
    "                  vmin=0 if cm else None, vmax=255 if cm else None)\n"
    "        ax.axis('off')\n"
    "        for sp2 in ax.spines.values():\n"
    "            sp2.set_edgecolor(c); sp2.set_linewidth(2); sp2.set_visible(True)\n"
    "    axes[row,0].set_ylabel(f'{cls}\\n{rp.stem}', fontsize=8, fontweight='bold',\n"
    "                            color=c, rotation=0, labelpad=80, va='center')\n"
    "    axes[row,3].set_xlabel(f'Coverage: {cov:.1f}%', fontsize=8, color=c, labelpad=4)\n"
    "legend_patches = [\n"
    "    Patch(facecolor='#2196F3', alpha=0.7, label='Class 1 - Egg boundary'),\n"
    "    Patch(facecolor='#F44336', alpha=0.7, label='Class 2 - Embryo/Vascular'),\n"
    "    Patch(facecolor='#CCCCCC', label='No structure detected (infertile)'),\n"
    "]\n"
    "fig.legend(handles=legend_patches, loc='lower center', ncol=3,\n"
    "           fontsize=9, framealpha=0.9, bbox_to_anchor=(0.5,-0.02))\n"
    "plt.tight_layout(h_pad=0.5, w_pad=0.3)\n"
    "plt.savefig('../docs/fig_unet_masking_samples.png', dpi=180,\n"
    "            bbox_inches='tight', facecolor=BG)\n"
    "plt.show()\n"
)

# ── markdown: t-SNE ───────────────────────────────────────────────────
md_tsne = {
    "cell_type": "markdown",
    "metadata": {},
    "source": (
        "## 15. t-SNE Cluster Visualization (73-D Feature Space)\n\n"
        "t-SNE mereduksi 73-D hybrid features ke 2 dimensi.\n\n"
        "| Panel | Isi |\n"
        "|-------|-----|\n"
        "| **Kiri** | Label kelas asli (Fertile=biru, Infertile=merah) |\n"
        "| **Tengah** | Prediksi K-Means (benar/salah) |\n"
        "| **Kanan** | Prediksi FCM/AWC (benar/salah) |\n\n"
        "> FCM menunjukkan lebih sedikit X (kesalahan) di zona overlap, "
        "membuktikan keunggulan soft-assignment untuk data yang ambigu."
    ),
}

# ── code: t-SNE ───────────────────────────────────────────────────────
tsne_code = (
    "import numpy as np, pickle, sys, warnings\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.lines as mlines\n"
    "from matplotlib.patches import Patch\n"
    "from sklearn.manifold import TSNE\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "warnings.filterwarnings('ignore')\n"
    "sys.path.insert(0, '..')\n"
    "\n"
    "BG='#FAFAFA'; C_FCM='#2A9D8F'; C_KM='#F4A261'; C_F='#1565C0'; C_I='#C62828'\n"
    "\n"
    "X_tr = np.load('../data/features/awc_features.npy')\n"
    "y_tr = np.load('../data/features/awc_labels.npy')\n"
    "X_te = np.load('../data/features/awc_test_features.npy')\n"
    "y_te = np.load('../data/features/awc_test_labels.npy')\n"
    "X_all = np.vstack([X_tr,X_te]); y_all = np.hstack([y_tr,y_te])\n"
    "is_test = np.array([False]*len(X_tr)+[True]*len(X_te))\n"
    "\n"
    "with open('../models/awc/awc_model.pkl','rb') as f:       awc = pickle.load(f)\n"
    "with open('../models/baselines/kmeans_model.pkl','rb') as f: km  = pickle.load(f)\n"
    "awc_pred = awc.predict(X_all); km_pred = km.predict(X_all)\n"
    "print(f'AWC: {(awc_pred==y_all).mean():.1%} | KMeans: {(km_pred==y_all).mean():.1%}')\n"
    "\n"
    "X_2d = TSNE(n_components=2, perplexity=25, n_iter=1000,\n"
    "            random_state=42, learning_rate='auto', init='pca'\n"
    "            ).fit_transform(StandardScaler().fit_transform(X_all))\n"
    "\n"
    "fig, axes = plt.subplots(1, 3, figsize=(16,5.5), facecolor=BG)\n"
    "fig.suptitle('t-SNE Visualization of Hybrid Deep Embedding Features (73-D)\\n'\n"
    "             'K-Means & FCM Cluster Separation',\n"
    "             fontsize=13, fontweight='bold')\n"
    "\n"
    "S_TR,S_TE,A_TR,A_TE = 55,110,0.75,1.0\n"
    "ax = axes[0]\n"
    "for cls,col in [(1,C_F),(0,C_I)]:\n"
    "    ax.scatter(X_2d[(y_all==cls)&~is_test,0], X_2d[(y_all==cls)&~is_test,1],\n"
    "               c=col,s=S_TR,alpha=A_TR,edgecolors='white',lw=0.5,zorder=3)\n"
    "    ax.scatter(X_2d[(y_all==cls)&is_test,0],  X_2d[(y_all==cls)&is_test,1],\n"
    "               c=col,s=S_TE,alpha=A_TE,edgecolors='black',lw=1.2,marker='D',zorder=4)\n"
    "ax.legend(handles=[Patch(color=C_F,label='Fertile'),Patch(color=C_I,label='Infertile'),\n"
    "          mlines.Line2D([],[],marker='D',color='w',markerfacecolor='#888',ms=9,label='Test')],\n"
    "          fontsize=9,framealpha=0.95)\n"
    "ax.set_title('True Class Labels',fontsize=12,fontweight='bold')\n"
    "\n"
    "for ax,pred,col_m,nm in [(axes[1],km_pred,C_KM,'K-Means'),(axes[2],awc_pred,C_FCM,'FCM (AWC)')]:\n"
    "    correct=pred==y_all; acc=correct.mean()\n"
    "    for msk,col,mk,sz,al,ec,z in [\n"
    "        (correct&~is_test,  col_m,'o',S_TR,  A_TR,'white',3),\n"
    "        (correct&is_test,   col_m,'D',S_TE,  A_TE,'black',4),\n"
    "        (~correct&~is_test,'#999','X',S_TR+10,0.9,'white',5),\n"
    "        (~correct&is_test, '#444','X',S_TE+10,1.0,'black',6),\n"
    "    ]:\n"
    "        idx=np.where(msk)[0]\n"
    "        if len(idx): ax.scatter(X_2d[idx,0],X_2d[idx,1],c=col,s=sz,\n"
    "                                alpha=al,marker=mk,edgecolors=ec,lw=0.8,zorder=z)\n"
    "    ax.text(0.03,0.96,f'Accuracy: {acc:.1%}',transform=ax.transAxes,\n"
    "            va='top',ha='left',fontsize=11,fontweight='bold',\n"
    "            bbox=dict(boxstyle='round,pad=0.3',fc='white',ec=col_m,lw=1.8,alpha=0.95))\n"
    "    ax.legend(handles=[Patch(color=col_m,label=f'Correct ({correct.sum()})'),\n"
    "              mlines.Line2D([],[],marker='X',color='w',markerfacecolor='#888',ms=9,\n"
    "                            label=f'Incorrect ({(~correct).sum()})')],\n"
    "              fontsize=9,framealpha=0.95)\n"
    "    ax.set_title(f'{nm} Cluster Predictions',fontsize=12,fontweight='bold')\n"
    "\n"
    "for ax in axes:\n"
    "    ax.set_xlabel('t-SNE Dim 1',fontsize=10); ax.set_ylabel('t-SNE Dim 2',fontsize=10)\n"
    "    ax.set_facecolor(BG); ax.grid(True,alpha=0.3,linestyle='--'); ax.set_axisbelow(True)\n"
    "    for sp in ax.spines.values(): sp.set_visible(False)\n"
    "\n"
    "plt.tight_layout(pad=2)\n"
    "plt.savefig('../docs/fig_tsne_cluster.png',dpi=200,bbox_inches='tight',facecolor=BG)\n"
    "plt.show()\n"
)

def make_code_cell(src):
    return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

# Insert before the last cell (conclusion markdown)
insert_pos = len(nb["cells"]) - 1
nb["cells"] = (
    nb["cells"][:insert_pos]
    + [md_masking, make_code_cell(masking_code),
       md_tsne,    make_code_cell(tsne_code)]
    + nb["cells"][insert_pos:]
)

with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Done. Total cells: {len(nb['cells'])}")
