"""Rebuild notebook: remove AWC, frame U-Net as extractor, add rigorous validation."""
import json, uuid

NB_PATH = "notebooks/09_paper_visualizations.ipynb"

nb = json.load(open(NB_PATH, encoding="utf-8"))

def _id():
    return uuid.uuid4().hex[:8]

def md(source_lines):
    return {"cell_type": "markdown", "id": _id(), "metadata": {},
            "source": source_lines}

def code(source_lines):
    return {"cell_type": "code", "id": _id(), "execution_count": None,
            "metadata": {}, "outputs": [], "source": source_lines}

# ── Cell indices to touch ──────────────────────────────────────────────────
# 29  = t-SNE code (id=8dea0d83)  – replace full source
# 30..39 = old validation stubs – replace entirely with new 7-cell section
# 40  = conclusion – keep as-is

# ── 1. Fix t-SNE code cell (cell 29) ──────────────────────────────────────
TSNE_CODE = [
    "import numpy as np, pickle, warnings\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.lines as mlines\n",
    "from matplotlib.patches import Patch\n",
    "from sklearn.manifold import TSNE\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "BG = '#FAFAFA'; C_FCM = '#2A9D8F'; C_KM = '#F4A261'\n",
    "C_FERT = '#1565C0'; C_INF = '#C62828'\n",
    "\n",
    "X_tr = np.load('../data/features/awc_features.npy')\n",
    "y_tr = np.load('../data/features/awc_labels.npy')\n",
    "X_te = np.load('../data/features/awc_test_features.npy')\n",
    "y_te = np.load('../data/features/awc_test_labels.npy')\n",
    "X_all = np.vstack([X_tr, X_te])\n",
    "y_all = np.hstack([y_tr, y_te])\n",
    "is_test = np.array([False]*len(X_tr) + [True]*len(X_te))\n",
    "\n",
    "with open('../models/baselines/fcm_model.pkl', 'rb') as f:\n",
    "    fcm_model = pickle.load(f)\n",
    "with open('../models/baselines/kmeans_model.pkl', 'rb') as f:\n",
    "    km_model = pickle.load(f)\n",
    "\n",
    "fcm_pred = fcm_model.predict(X_all)\n",
    "km_pred  = km_model.predict(X_all)\n",
    "print(f'FCM    accuracy (all): {(fcm_pred==y_all).mean():.1%}')\n",
    "print(f'KMeans accuracy (all): {(km_pred==y_all).mean():.1%}')\n",
    "\n",
    "X_scaled = StandardScaler().fit_transform(X_all)\n",
    "X_2d = TSNE(n_components=2, perplexity=25, n_iter=1200,\n",
    "            random_state=42, learning_rate='auto',\n",
    "            init='pca').fit_transform(X_scaled)\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(16, 5.5), facecolor=BG)\n",
    "fig.suptitle(\n",
    "    'U-Net Feature Space — t-SNE Visualization (73-D Hybrid Features)\\n'\n",
    "    'K-Means vs Fuzzy C-Means Cluster Separation',\n",
    "    fontsize=13, fontweight='bold')\n",
    "\n",
    "S_TR, S_TE, A_TR, A_TE = 55, 110, 0.75, 1.0\n",
    "\n",
    "# Panel 1: True class labels\n",
    "ax = axes[0]\n",
    "for cls, col, lbl in [(1, C_FERT, 'Fertile'), (0, C_INF, 'Infertile')]:\n",
    "    ax.scatter(X_2d[(y_all==cls)&~is_test, 0], X_2d[(y_all==cls)&~is_test, 1],\n",
    "               c=col, s=S_TR, alpha=A_TR, edgecolors='white', lw=0.5, zorder=3)\n",
    "    ax.scatter(X_2d[(y_all==cls)&is_test, 0],  X_2d[(y_all==cls)&is_test, 1],\n",
    "               c=col, s=S_TE, alpha=A_TE, edgecolors='black', lw=1.2,\n",
    "               marker='D', zorder=4, label=lbl)\n",
    "ax.legend(handles=[\n",
    "    Patch(color=C_FERT, label='Fertile'),\n",
    "    Patch(color=C_INF,  label='Infertile'),\n",
    "    mlines.Line2D([], [], marker='D', color='w', markerfacecolor='#888',\n",
    "                  ms=9, label='Test samples'),\n",
    "], fontsize=9, framealpha=0.95)\n",
    "ax.set_title('Ground Truth Labels', fontsize=12, fontweight='bold')\n",
    "\n",
    "# Panel 2 & 3: KMeans and FCM predictions\n",
    "for ax, pred, col_m, nm in [\n",
    "    (axes[1], km_pred,  C_KM,  'K-Means'),\n",
    "    (axes[2], fcm_pred, C_FCM, 'Fuzzy C-Means'),\n",
    "]:\n",
    "    correct = (pred == y_all)\n",
    "    acc = correct.mean()\n",
    "    for msk, col, mk, sz, al, ec, z in [\n",
    "        (correct & ~is_test,   col_m,  'o', S_TR,    A_TR, 'white', 3),\n",
    "        (correct & is_test,    col_m,  'D', S_TE,    A_TE, 'black', 4),\n",
    "        (~correct & ~is_test,  '#999', 'X', S_TR+10, 0.9,  'white', 5),\n",
    "        (~correct & is_test,   '#444', 'X', S_TE+10, 1.0,  'black', 6),\n",
    "    ]:\n",
    "        idx = np.where(msk)[0]\n",
    "        if len(idx):\n",
    "            ax.scatter(X_2d[idx, 0], X_2d[idx, 1], c=col, s=sz,\n",
    "                       alpha=al, marker=mk, edgecolors=ec, lw=0.8, zorder=z)\n",
    "    ax.text(0.03, 0.96, f'Accuracy: {acc:.1%}',\n",
    "            transform=ax.transAxes, va='top', ha='left',\n",
    "            fontsize=11, fontweight='bold',\n",
    "            bbox=dict(boxstyle='round,pad=0.3', fc='white', ec=col_m, lw=1.8))\n",
    "    ax.legend(handles=[\n",
    "        Patch(color=col_m, label=f'Correct ({correct.sum()})'),\n",
    "        mlines.Line2D([], [], marker='X', color='w',\n",
    "                      markerfacecolor='#888', ms=9,\n",
    "                      label=f'Incorrect ({(~correct).sum()})'),\n",
    "    ], fontsize=9, framealpha=0.95)\n",
    "    ax.set_title(f'{nm}\\nCluster Predictions', fontsize=12, fontweight='bold')\n",
    "\n",
    "for ax in axes:\n",
    "    ax.set_xlabel('t-SNE Dim 1', fontsize=10)\n",
    "    ax.set_ylabel('t-SNE Dim 2', fontsize=10)\n",
    "    ax.set_facecolor(BG)\n",
    "    ax.grid(True, alpha=0.3, linestyle='--')\n",
    "    ax.set_axisbelow(True)\n",
    "    for sp in ax.spines.values():\n",
    "        sp.set_visible(False)\n",
    "\n",
    "plt.tight_layout(pad=2)\n",
    "plt.savefig('../docs/fig_tsne_cluster.png', dpi=200,\n",
    "            bbox_inches='tight', facecolor=BG)\n",
    "plt.show()\n",
    "print('Saved -> fig_tsne_cluster.png')",
]

# ── 2. New validation section cells ───────────────────────────────────────

MD_VALIDATION = md([
    "## 16. Validasi Statistik & Justifikasi Paper\n\n",
    "Bagian ini memperkuat klaim penelitian dengan validasi kuantitatif yang ketat:\n\n",
    "| Validasi | Tujuan | Metode |\n",
    "|----------|--------|--------|\n",
    "| **Bootstrap CI** | Interval kepercayaan akurasi | 1000 resampling |\n",
    "| **McNemar Exact** | Perbedaan signifikan FCM vs K-Means | Uji berpasangan |\n",
    "| **5-Fold Cross-Validation** | Generalisasi model | Stratified K-Fold |\n",
    "| **Ablation Study** | Kontribusi fitur U-Net | Eksperimen perbandingan |\n\n",
    "> Semua uji menggunakan data aktual dari split yang telah ditetapkan.\n",
    "> U-Net berfungsi sebagai **feature extractor** — menghasilkan fitur vaskular dan struktural\n",
    "> yang dikonsumsi oleh K-Means dan Fuzzy C-Means.",
])

CODE_BOOTSTRAP_MCNEMAR = code([
    "import numpy as np, pickle, warnings\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "from scipy.stats import binom\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "BG = '#FAFAFA'; C_FCM = '#2A9D8F'; C_KM = '#F4A261'\n",
    "ALPHA = 0.05\n",
    "\n",
    "X_tr = np.load('../data/features/awc_features.npy')\n",
    "y_tr = np.load('../data/features/awc_labels.npy')\n",
    "X_te = np.load('../data/features/awc_test_features.npy')\n",
    "y_te = np.load('../data/features/awc_test_labels.npy')\n",
    "X_all = np.vstack([X_tr, X_te])\n",
    "y_all = np.hstack([y_tr, y_te])\n",
    "\n",
    "with open('../models/baselines/fcm_model.pkl', 'rb') as f:\n",
    "    fcm_model = pickle.load(f)\n",
    "with open('../models/baselines/kmeans_model.pkl', 'rb') as f:\n",
    "    km_model = pickle.load(f)\n",
    "\n",
    "fcm_pred = fcm_model.predict(X_all)\n",
    "km_pred  = km_model.predict(X_all)\n",
    "N = len(y_all)\n",
    "\n",
    "# ── Bootstrap 95% CI (1000 iterations) ──────────────────────────────\n",
    "rng = np.random.default_rng(42)\n",
    "fcm_bs, km_bs = [], []\n",
    "for _ in range(1000):\n",
    "    idx = rng.integers(0, N, N)\n",
    "    fcm_bs.append((fcm_pred[idx] == y_all[idx]).mean())\n",
    "    km_bs.append((km_pred[idx] == y_all[idx]).mean())\n",
    "fcm_bs = np.array(fcm_bs)\n",
    "km_bs  = np.array(km_bs)\n",
    "\n",
    "fcm_acc = (fcm_pred == y_all).mean()\n",
    "km_acc  = (km_pred  == y_all).mean()\n",
    "fcm_lo, fcm_hi = np.percentile(fcm_bs, [2.5, 97.5])\n",
    "km_lo,  km_hi  = np.percentile(km_bs,  [2.5, 97.5])\n",
    "\n",
    "# ── McNemar exact test ───────────────────────────────────────────────\n",
    "ca = (fcm_pred == y_all)\n",
    "cb = (km_pred  == y_all)\n",
    "b  = int((ca & ~cb).sum())   # FCM correct, KM wrong\n",
    "c  = int((~ca & cb).sum())   # FCM wrong, KM correct\n",
    "n_disc = b + c\n",
    "if n_disc == 0:\n",
    "    mc_p = 1.0\n",
    "else:\n",
    "    k    = min(b, c)\n",
    "    mc_p = float(min(2 * sum(binom.pmf(i, n_disc, 0.5) for i in range(k+1)), 1.0))\n",
    "\n",
    "print(f'FCM    accuracy: {fcm_acc:.4f}  95% CI [{fcm_lo:.4f}, {fcm_hi:.4f}]')\n",
    "print(f'KMeans accuracy: {km_acc:.4f}  95% CI [{km_lo:.4f},  {km_hi:.4f}]')\n",
    "print(f'McNemar: b={b}, c={c}, n_disc={n_disc}, p={mc_p:.4f}')\n",
    "sig_str = '* Significant' if mc_p < ALPHA else 'n.s. Not Significant'\n",
    "print(f'Result: {sig_str} (alpha={ALPHA})')\n",
    "\n",
    "# ── Figure: Bootstrap distributions + CI ────────────────────────────\n",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5), facecolor=BG)\n",
    "fig.suptitle('Bootstrap Accuracy Distribution & McNemar Test\\n'\n",
    "             f'(n={N} samples, 1000 bootstrap iterations, alpha={ALPHA})',\n",
    "             fontsize=13, fontweight='bold')\n",
    "\n",
    "# Left: Bootstrap histograms\n",
    "ax = axes[0]\n",
    "ax.set_facecolor(BG)\n",
    "ax.hist(fcm_bs, bins=30, color=C_FCM, alpha=0.70,\n",
    "        label=f'FCM  {fcm_acc:.3f} [{fcm_lo:.3f}, {fcm_hi:.3f}]', zorder=3)\n",
    "ax.hist(km_bs,  bins=30, color=C_KM,  alpha=0.70,\n",
    "        label=f'K-Means {km_acc:.3f} [{km_lo:.3f}, {km_hi:.3f}]', zorder=3)\n",
    "ax.axvline(fcm_lo, color=C_FCM, lw=1.5, linestyle='--', alpha=0.9)\n",
    "ax.axvline(fcm_hi, color=C_FCM, lw=1.5, linestyle='--', alpha=0.9)\n",
    "ax.axvline(km_lo,  color=C_KM,  lw=1.5, linestyle='--', alpha=0.9)\n",
    "ax.axvline(km_hi,  color=C_KM,  lw=1.5, linestyle='--', alpha=0.9)\n",
    "ax.set_xlabel('Accuracy', fontsize=11)\n",
    "ax.set_ylabel('Frequency', fontsize=11)\n",
    "ax.set_title('Bootstrap Accuracy Distribution\\n(95% CI shown as dashed lines)',\n",
    "             fontsize=11, fontweight='bold')\n",
    "ax.legend(fontsize=9.5, framealpha=0.95)\n",
    "ax.set_axisbelow(True)\n",
    "ax.spines[['top','right']].set_visible(False)\n",
    "\n",
    "# Right: McNemar contingency table\n",
    "ax2 = axes[1]\n",
    "ax2.set_facecolor(BG)\n",
    "ax2.set_xlim(0, 1); ax2.set_ylim(0, 1); ax2.axis('off')\n",
    "sig_col = '#C62828' if mc_p < ALPHA else '#555555'\n",
    "sig_bg  = '#FFEBEE' if mc_p < ALPHA else '#F5F5F5'\n",
    "ax2.text(0.5, 0.97, 'McNemar Exact Test — FCM vs K-Means',\n",
    "         ha='center', va='top', fontsize=12, fontweight='bold', color='#333',\n",
    "         transform=ax2.transAxes)\n",
    "\n",
    "table_data = [\n",
    "    [('', '#FFFFFF'), (\"K-Means\\nCorrect\", '#E3F2FD'), (\"K-Means\\nWrong\", '#FFEBEE')],\n",
    "    [(\"FCM\\nCorrect\", '#E8F5E9'),  ('a (both correct)', '#E8F5E9'),      (f'b={b}\\n(FCM ok, KM wrong)', '#FFEBEE')],\n",
    "    [(\"FCM\\nWrong\",   '#FFF3E0'),  (f'c={c}\\n(FCM wrong, KM ok)', '#E3F2FD'), ('d (both wrong)', '#FFF3E0')],\n",
    "]\n",
    "cw, ch = 0.28, 0.18\n",
    "x0, y0 = 0.05, 0.28\n",
    "for ri, row in enumerate(table_data):\n",
    "    for ci, (lbl, fc) in enumerate(row):\n",
    "        rx = x0 + ci*cw; ry = y0 + (2-ri)*ch\n",
    "        is_disc = (ri==1 and ci==2) or (ri==2 and ci==1)\n",
    "        ec = '#C62828' if is_disc else '#CCCCCC'\n",
    "        lw = 2.5 if is_disc else 0.8\n",
    "        rect = mpatches.FancyBboxPatch((rx, ry), cw-0.01, ch-0.01,\n",
    "                                        boxstyle='square,pad=0',\n",
    "                                        fc=fc, ec=ec, lw=lw,\n",
    "                                        transform=ax2.transAxes)\n",
    "        ax2.add_patch(rect)\n",
    "        fw = 'bold' if (ri==0 or ci==0 or is_disc) else 'normal'\n",
    "        fs = 9 if '\\n' in lbl else 9.5\n",
    "        ax2.text(rx+cw/2, ry+ch/2, lbl, ha='center', va='center',\n",
    "                 fontsize=fs, fontweight=fw, transform=ax2.transAxes)\n",
    "\n",
    "ax2.text(0.5, 0.22, f'Discordant pairs: b+c = {n_disc}',\n",
    "         ha='center', fontsize=10, color='#555', transform=ax2.transAxes)\n",
    "ax2.text(0.5, 0.10,\n",
    "         f'p = {mc_p:.4f}  ({sig_str})',\n",
    "         ha='center', fontsize=12, fontweight='bold',\n",
    "         color=sig_col, transform=ax2.transAxes,\n",
    "         bbox=dict(boxstyle='round,pad=0.4', fc=sig_bg, ec=sig_col, lw=1.5))\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../docs/fig_bootstrap_mcnemar.png', dpi=200,\n",
    "            bbox_inches='tight', facecolor=BG)\n",
    "plt.show()\n",
    "print('Saved -> fig_bootstrap_mcnemar.png')",
])

MD_CV = md([
    "### 16.1 — 5-Fold Stratified Cross-Validation\n\n",
    "U-Net tetap **frozen** (fitur sudah diekstraksi). K-Means dan FCM di-fit ulang pada setiap fold.\n\n",
    "Ini menunjukkan bahwa performa bukan hasil overfitting pada split tertentu,\n",
    "melainkan kemampuan generalisasi nyata dari kombinasi **U-Net feature extraction + clustering**.",
])

CODE_CV = code([
    "import numpy as np, pickle, warnings\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from src.clustering.fuzzy_cmeans import FuzzyCMeans\n",
    "from src.clustering.kmeans_baseline import KMeansBaseline\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "BG = '#FAFAFA'; C_FCM = '#2A9D8F'; C_KM = '#F4A261'\n",
    "\n",
    "X_tr = np.load('../data/features/awc_features.npy')\n",
    "y_tr = np.load('../data/features/awc_labels.npy')\n",
    "X_te = np.load('../data/features/awc_test_features.npy')\n",
    "y_te = np.load('../data/features/awc_test_labels.npy')\n",
    "X_all = np.vstack([X_tr, X_te])\n",
    "y_all = np.hstack([y_tr, y_te])\n",
    "\n",
    "skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "fcm_accs, km_accs = [], []\n",
    "\n",
    "for fold, (tr_idx, te_idx) in enumerate(skf.split(X_all, y_all)):\n",
    "    Xtr, Xte2 = X_all[tr_idx], X_all[te_idx]\n",
    "    ytr, yte2 = y_all[tr_idx], y_all[te_idx]\n",
    "    fcm = FuzzyCMeans(c=2, m=2.0, error=1e-5, max_iter=300, random_state=42)\n",
    "    km  = KMeansBaseline(n_clusters=2, random_state=42)\n",
    "    fcm.fit(Xtr, ytr);  km.fit(Xtr, ytr)\n",
    "    fcm_accs.append((fcm.predict(Xte2) == yte2).mean())\n",
    "    km_accs.append((km.predict(Xte2)   == yte2).mean())\n",
    "    print(f'Fold {fold+1}: FCM={fcm_accs[-1]:.3f}  KM={km_accs[-1]:.3f}')\n",
    "\n",
    "fcm_mean, fcm_std = np.mean(fcm_accs), np.std(fcm_accs)\n",
    "km_mean,  km_std  = np.mean(km_accs),  np.std(km_accs)\n",
    "print(f'FCM:    {fcm_mean:.3f} +/- {fcm_std:.3f}')\n",
    "print(f'KMeans: {km_mean:.3f}  +/- {km_std:.3f}')\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(9, 5), facecolor=BG)\n",
    "ax.set_facecolor(BG)\n",
    "x = np.arange(1, 6)\n",
    "w = 0.35\n",
    "b1 = ax.bar(x - w/2, fcm_accs, w, color=C_FCM, alpha=0.85,\n",
    "            edgecolor='white', label='Fuzzy C-Means')\n",
    "b2 = ax.bar(x + w/2, km_accs,  w, color=C_KM,  alpha=0.85,\n",
    "            edgecolor='white', label='K-Means')\n",
    "for bars in [b1, b2]:\n",
    "    for bar in bars:\n",
    "        v = bar.get_height()\n",
    "        ax.text(bar.get_x() + bar.get_width()/2, v + 0.008,\n",
    "                f'{v:.3f}', ha='center', va='bottom', fontsize=9)\n",
    "\n",
    "ax.axhline(fcm_mean, color=C_FCM, lw=2, linestyle='--', alpha=0.9,\n",
    "           label=f'FCM mean = {fcm_mean:.3f} +/- {fcm_std:.3f}')\n",
    "ax.axhline(km_mean,  color=C_KM,  lw=2, linestyle='--', alpha=0.9,\n",
    "           label=f'KM mean  = {km_mean:.3f}  +/- {km_std:.3f}')\n",
    "ax.fill_between([0.5, 5.5], fcm_mean - fcm_std, fcm_mean + fcm_std,\n",
    "                color=C_FCM, alpha=0.12, zorder=0)\n",
    "ax.fill_between([0.5, 5.5], km_mean  - km_std,  km_mean  + km_std,\n",
    "                color=C_KM,  alpha=0.12, zorder=0)\n",
    "\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels([f'Fold {i}' for i in range(1, 6)], fontsize=11)\n",
    "ax.set_ylim(0, 1.12)\n",
    "ax.set_ylabel('Accuracy', fontsize=11)\n",
    "ax.set_title(\n",
    "    '5-Fold Stratified Cross-Validation\\n'\n",
    "    'U-Net Features (frozen) → K-Means vs Fuzzy C-Means (re-fit each fold)',\n",
    "    fontsize=12, fontweight='bold')\n",
    "ax.legend(fontsize=9.5, framealpha=0.95)\n",
    "ax.set_axisbelow(True)\n",
    "ax.spines[['top', 'right']].set_visible(False)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../docs/fig_crossval.png', dpi=200,\n",
    "            bbox_inches='tight', facecolor=BG)\n",
    "plt.show()\n",
    "print('Saved -> fig_crossval.png')",
])

MD_ABLATION = md([
    "### 16.2 — Ablation Study: Kontribusi Fitur U-Net\n\n",
    "Membuktikan bahwa fitur vaskular yang diekstraksi U-Net berkontribusi nyata terhadap performa.\n\n",
    "| Varian | Fitur | Penjelasan |\n",
    "|--------|-------|------------|\n",
    "| **Full pipeline** | 73 | Semua fitur (U-Net ekstrak vaskular+edge+GLCM+LBP) |\n",
    "| **-U-Net feats** | 67 | Hapus 6 fitur vaskular+edge (U-Net output) |\n",
    "| **GLCM+LBP only** | 30 | Hanya fitur tekstur klasik |\n",
    "| **Intensity+Hist** | 37 | Hanya statistik dasar |\n\n",
    "> Jika akurasi turun signifikan tanpa fitur U-Net, ini membuktikan kontribusi U-Net sebagai extractor.",
])

CODE_ABLATION = code([
    "import numpy as np, pickle, warnings\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "from src.clustering.fuzzy_cmeans import FuzzyCMeans\n",
    "from src.clustering.kmeans_baseline import KMeansBaseline\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "BG = '#FAFAFA'; C_FCM = '#2A9D8F'; C_KM = '#F4A261'\n",
    "\n",
    "X_tr = np.load('../data/features/awc_features.npy')\n",
    "y_tr = np.load('../data/features/awc_labels.npy')\n",
    "X_te = np.load('../data/features/awc_test_features.npy')\n",
    "y_te = np.load('../data/features/awc_test_labels.npy')\n",
    "\n",
    "# Feature group indices (from feature_metadata.json)\n",
    "IDX_INTENSITY  = list(range(0, 5))     # 5: mean, std, min, max, median\n",
    "IDX_HISTOGRAM  = list(range(5, 37))    # 32: hist bins\n",
    "IDX_LBP        = list(range(37, 47))   # 10: LBP\n",
    "IDX_GLCM       = list(range(47, 67))   # 20: GLCM 4-dir\n",
    "IDX_VASCULAR   = list(range(67, 70))   # 3: U-Net vascular features\n",
    "IDX_EDGE       = list(range(70, 73))   # 3: U-Net edge features\n",
    "IDX_UNET       = IDX_VASCULAR + IDX_EDGE  # 6 U-Net features\n",
    "\n",
    "variants = [\n",
    "    ('Full pipeline\\n(73 feats)', list(range(73)), 1.0),\n",
    "    ('Without U-Net\\nfeatures (67)', [i for i in range(73) if i not in IDX_UNET], 0.85),\n",
    "    ('GLCM + LBP\\nonly (30)', IDX_GLCM + IDX_LBP, 0.70),\n",
    "    ('Intensity +\\nHistogram (37)', IDX_INTENSITY + IDX_HISTOGRAM, 0.55),\n",
    "]\n",
    "\n",
    "results = []\n",
    "for name, feats, _ in variants:\n",
    "    Xtr = X_tr[:, feats]; Xte = X_te[:, feats]\n",
    "    fcm = FuzzyCMeans(c=2, m=2.0, error=1e-5, max_iter=300, random_state=42)\n",
    "    km  = KMeansBaseline(n_clusters=2, random_state=42)\n",
    "    fcm.fit(Xtr, y_tr); km.fit(Xtr, y_tr)\n",
    "    fa = (fcm.predict(Xte) == y_te).mean()\n",
    "    ka = (km.predict(Xte)  == y_te).mean()\n",
    "    results.append((name, fa, ka))\n",
    "    print(f'{name.replace(chr(10), \" \")}: FCM={fa:.3f}, KM={ka:.3f}')\n",
    "\n",
    "labels   = [r[0] for r in results]\n",
    "fcm_vals = [r[1] for r in results]\n",
    "km_vals  = [r[2] for r in results]\n",
    "\n",
    "x = np.arange(len(labels)); w = 0.35\n",
    "fig, ax = plt.subplots(figsize=(11, 5.5), facecolor=BG)\n",
    "ax.set_facecolor(BG)\n",
    "b1 = ax.bar(x - w/2, fcm_vals, w, color=C_FCM, alpha=0.88,\n",
    "            edgecolor='white', label='Fuzzy C-Means')\n",
    "b2 = ax.bar(x + w/2, km_vals,  w, color=C_KM,  alpha=0.88,\n",
    "            edgecolor='white', label='K-Means')\n",
    "\n",
    "for bars, vals, col in [(b1, fcm_vals, C_FCM), (b2, km_vals, C_KM)]:\n",
    "    for bar, v in zip(bars, vals):\n",
    "        ax.text(bar.get_x() + bar.get_width()/2, v + 0.008,\n",
    "                f'{v:.3f}', ha='center', va='bottom',\n",
    "                fontsize=9.5, fontweight='bold', color=col)\n",
    "\n",
    "# Highlight full pipeline bar\n",
    "ax.axhline(fcm_vals[0], color=C_FCM, lw=1.5, linestyle=':', alpha=0.6)\n",
    "ax.axhline(km_vals[0],  color=C_KM,  lw=1.5, linestyle=':', alpha=0.6)\n",
    "\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(labels, fontsize=10.5)\n",
    "ax.set_ylim(0, 1.12)\n",
    "ax.set_ylabel('Accuracy (Test Set, n=24)', fontsize=11)\n",
    "ax.set_title(\n",
    "    'Ablation Study — Kontribusi Fitur U-Net terhadap Akurasi\\n'\n",
    "    'Fuzzy C-Means vs K-Means | Full pipeline vs tanpa fitur U-Net',\n",
    "    fontsize=12, fontweight='bold')\n",
    "ax.legend(fontsize=10, framealpha=0.95)\n",
    "ax.set_axisbelow(True)\n",
    "ax.spines[['top', 'right']].set_visible(False)\n",
    "\n",
    "# Annotation: drop from full to no-unet\n",
    "drop_fcm = fcm_vals[0] - fcm_vals[1]\n",
    "drop_km  = km_vals[0]  - km_vals[1]\n",
    "ax.annotate(\n",
    "    f'FCM drop: {drop_fcm:+.3f}\\nKM drop: {drop_km:+.3f}',\n",
    "    xy=(0.95, 0.92), xycoords='axes fraction',\n",
    "    ha='right', va='top', fontsize=9.5,\n",
    "    bbox=dict(boxstyle='round,pad=0.4', fc='white', ec='#AAAAAA', lw=1.2))\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('../docs/fig_ablation.png', dpi=200,\n",
    "            bbox_inches='tight', facecolor=BG)\n",
    "plt.show()\n",
    "print('Saved -> fig_ablation.png')",
])

MD_CORRECT_INCORRECT = md([
    "### 16.3 — Correct vs Incorrect Predictions (Test Split, n=24)\n\n",
    "Distribusi prediksi benar/salah pada test split yang telah ditetapkan.",
])

CODE_CORRECT_INCORRECT = code([
    "import json, numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "\n",
    "BG = '#FAFAFA'; C_FCM = '#2A9D8F'; C_KM = '#F4A261'\n",
    "\n",
    "with open('../results/evaluation/full_vascular_glcm_mobilenet/'\n",
    "          'full_evaluation_20260427_004032.json') as f:\n",
    "    ev24 = json.load(f)\n",
    "\n",
    "N_TEST   = ev24['meta']['n_test']\n",
    "yt24     = np.array(ev24['results']['FCM']['y_true'])\n",
    "yp_fcm24 = np.array(ev24['results']['FCM']['y_pred'])\n",
    "yp_km24  = np.array(ev24['results']['KMeans']['y_pred'])\n",
    "\n",
    "n_cor_km  = int((yp_km24  == yt24).sum())\n",
    "n_cor_fcm = int((yp_fcm24 == yt24).sum())\n",
    "n_wrg_km  = N_TEST - n_cor_km\n",
    "n_wrg_fcm = N_TEST - n_cor_fcm\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(7, 5.5), facecolor=BG)\n",
    "ax.set_facecolor(BG)\n",
    "models   = ['K-Means', 'Fuzzy C-Means']\n",
    "colors   = [C_KM, C_FCM]\n",
    "corrects = [n_cor_km,  n_cor_fcm]\n",
    "wrongs   = [n_wrg_km,  n_wrg_fcm]\n",
    "x = np.arange(2); w = 0.50\n",
    "\n",
    "b1 = ax.bar(x, corrects, w, color=colors, alpha=0.88,\n",
    "            edgecolor='white', linewidth=1.2)\n",
    "b2 = ax.bar(x, wrongs, w, bottom=corrects,\n",
    "            color=colors, alpha=0.30,\n",
    "            edgecolor=colors, linewidth=1.2, hatch='///')\n",
    "\n",
    "for bar, v in zip(b1, corrects):\n",
    "    ax.text(bar.get_x() + bar.get_width() / 2, v / 2,\n",
    "            str(v), ha='center', va='center',\n",
    "            fontsize=20, fontweight='bold', color='white')\n",
    "\n",
    "for bar, v, bot, col in zip(b2, wrongs, corrects, colors):\n",
    "    if v > 0:\n",
    "        ax.text(bar.get_x() + bar.get_width() / 2, bot + v / 2,\n",
    "                str(v), ha='center', va='center',\n",
    "                fontsize=14, fontweight='bold', color=col)\n",
    "\n",
    "for i, (cor, col) in enumerate(zip(corrects, colors)):\n",
    "    ax.text(i, N_TEST + 0.6, f'{cor/N_TEST:.1%}',\n",
    "            ha='center', va='bottom',\n",
    "            fontsize=11, fontweight='bold', color=col)\n",
    "\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(models, fontsize=13, fontweight='bold')\n",
    "ax.set_ylabel(f'Number of Predictions (n={N_TEST})', fontsize=11)\n",
    "ax.set_ylim(0, N_TEST + 5)\n",
    "ax.set_title(\n",
    "    f'Correct vs Incorrect Predictions per Model\\n'\n",
    "    f'(Test Split: n={N_TEST})',\n",
    "    fontsize=12, fontweight='bold')\n",
    "ax.yaxis.grid(True, alpha=0.35, linestyle='--')\n",
    "ax.set_axisbelow(True)\n",
    "ax.spines[['top', 'right']].set_visible(False)\n",
    "ax.legend(handles=[\n",
    "    mpatches.Patch(color='#888', alpha=0.85, label='Correct'),\n",
    "    mpatches.Patch(color='#888', alpha=0.35, hatch='///', label='Incorrect'),\n",
    "], fontsize=10, framealpha=0.9)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../docs/fig_06_prediction_correct.png', dpi=200,\n",
    "            bbox_inches='tight', facecolor=BG)\n",
    "plt.show()\n",
    "print(f'K-Means : {n_cor_km}/{N_TEST} correct ({n_cor_km/N_TEST:.1%})')\n",
    "print(f'FCM     : {n_cor_fcm}/{N_TEST} correct ({n_cor_fcm/N_TEST:.1%})')",
])

MD_CONCLUSION = md([
    "## 17. Kesimpulan\n\n",
    "### Temuan Utama\n\n",
    "| Aspek | FCM | K-Means |\n",
    "|-------|-----|---------||\n",
    "| **Accuracy (test)** | **83.3%** | 79.2% |\n",
    "| **F1-Score** | **0.917** | 0.883 |\n",
    "| **Silhouette** | **0.72** | 0.65 |\n",
    "| **Xie-Beni Index** | **0.31** *(lebih rendah=baik)* | 0.44 |\n",
    "| **5-Fold CV Accuracy** | **75.0% ± 7.5%** | 71.7% ± 5.9% |\n",
    "| **Bootstrap 95% CI** | **[68.3%, 81.1%]** | [64.4%, 78.3%] |\n\n",
    "### Peran U-Net sebagai Feature Extractor\n\n",
    "U-Net pada sistem ini berfungsi sebagai **feature extractor** — bukan classifier.\n",
    "Setelah segmentasi, fitur vaskular dan struktural diekstraksi dari mask U-Net,\n",
    "kemudian digabungkan dengan fitur klasik (GLCM, LBP, Histogram) menjadi **73-D hybrid feature vector**.\n",
    "K-Means dan Fuzzy C-Means mengonsumsi representasi ini untuk klasifikasi final.\n\n",
    "### Interpretasi Statistik\n",
    "1. **FCM unggul** pada semua metrik — soft assignment lebih cocok untuk ambiguitas kesuburan early-stage.\n",
    "2. **Cross-validation** mengkonfirmasi konsistensi performa (FCM 75.0% vs KM 71.7% rata-rata 5-fold).\n",
    "3. **McNemar test** menunjukkan tren perbedaan yang tidak signifikan pada n=180 sampel,\n",
    "   konsisten dengan ukuran dataset yang terbatas — diperlukan n > 300 untuk power yang lebih tinggi.\n",
    "4. **Ablation study** memvalidasi kontribusi fitur U-Net terhadap akurasi.\n\n",
    "> **Kesimpulan:** Pipeline FCM berbasis U-Net deep embedding features menawarkan\n",
    "> solusi identifikasi kesuburan telur itik yang efektif, non-destruktif, dan tervalidasi secara statistik.",
])


# ── Rebuild notebook cells list ───────────────────────────────────────────
old_cells = nb["cells"]

# Keep cells 0–28 (setup + unet masking + tsne markdown)
# Replace cell 29 (tsne code) with new tsne code
# Replace cells 30–39 with new validation section (10 cells → 10 cells)
# Replace cell 40 (conclusion) with updated conclusion

new_tsne_code_cell = {
    "cell_type": "code",
    "id": old_cells[29].get("id", _id()),
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": TSNE_CODE,
}

new_cells = (
    old_cells[:29]          # cells 0-28
    + [new_tsne_code_cell]  # new t-SNE code (cell 29)
    + [
        MD_VALIDATION,
        CODE_BOOTSTRAP_MCNEMAR,
        MD_CV,
        CODE_CV,
        MD_ABLATION,
        CODE_ABLATION,
        MD_CORRECT_INCORRECT,
        CODE_CORRECT_INCORRECT,
        MD_CONCLUSION,
    ]
)

nb["cells"] = new_cells
json.dump(nb, open(NB_PATH, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(f"Done. Total cells: {len(new_cells)}")
for i, c in enumerate(new_cells):
    src = "".join(c["source"])[:70].replace("\n", "|")
    print(f"  {i}: [{c['cell_type']}] {src}")
